// Curated public-figure list. Each entry is a Wikipedia article title — we
// pull the canonical thumbnail from /api/rest_v1/page/summary at import time.
//
// Spread across categories so the embedding space has visual variety; bias
// toward people whose Wikipedia infobox photo is a clean headshot.

export const CELEBRITIES = [
	// ── Hollywood — actors (men) ───────────────────────────────────────────────
	{ title: 'Tom Hanks', category: 'actor' },
	{ title: 'Denzel Washington', category: 'actor' },
	{ title: 'Brad Pitt', category: 'actor' },
	{ title: 'Leonardo DiCaprio', category: 'actor' },
	{ title: 'Robert Downey Jr.', category: 'actor' },
	{ title: 'Morgan Freeman', category: 'actor' },
	{ title: 'Tom Cruise', category: 'actor' },
	{ title: 'Will Smith', category: 'actor' },
	{ title: 'Johnny Depp', category: 'actor' },
	{ title: 'Keanu Reeves', category: 'actor' },
	{ title: 'Samuel L. Jackson', category: 'actor' },
	{ title: 'Hugh Jackman', category: 'actor' },
	{ title: 'Chris Hemsworth', category: 'actor' },
	{ title: 'Chris Evans (actor)', category: 'actor' },
	{ title: 'Chris Pratt', category: 'actor' },
	{ title: 'Ryan Reynolds', category: 'actor' },
	{ title: 'Ryan Gosling', category: 'actor' },
	{ title: 'Matt Damon', category: 'actor' },
	{ title: 'Ben Affleck', category: 'actor' },
	{ title: 'George Clooney', category: 'actor' },
	{ title: 'Anthony Hopkins', category: 'actor' },
	{ title: 'Idris Elba', category: 'actor' },
	{ title: 'Michael B. Jordan', category: 'actor' },
	{ title: 'Donald Glover', category: 'actor' },
	{ title: 'Mahershala Ali', category: 'actor' },
	{ title: 'Daniel Kaluuya', category: 'actor' },
	{ title: 'Timothée Chalamet', category: 'actor' },
	{ title: 'Tom Holland', category: 'actor' },
	{ title: 'Andrew Garfield', category: 'actor' },
	{ title: 'Jake Gyllenhaal', category: 'actor' },
	{ title: 'Christian Bale', category: 'actor' },
	{ title: 'Joaquin Phoenix', category: 'actor' },
	{ title: 'Adam Driver', category: 'actor' },
	{ title: 'Pedro Pascal', category: 'actor' },
	{ title: 'Oscar Isaac', category: 'actor' },

	// ── Hollywood — actresses ──────────────────────────────────────────────────
	{ title: 'Meryl Streep', category: 'actor' },
	{ title: 'Cate Blanchett', category: 'actor' },
	{ title: 'Julia Roberts', category: 'actor' },
	{ title: 'Nicole Kidman', category: 'actor' },
	{ title: 'Sandra Bullock', category: 'actor' },
	{ title: 'Charlize Theron', category: 'actor' },
	{ title: 'Halle Berry', category: 'actor' },
	{ title: 'Viola Davis', category: 'actor' },
	{ title: 'Lupita Nyong\'o', category: 'actor' },
	{ title: 'Octavia Spencer', category: 'actor' },
	{ title: 'Reese Witherspoon', category: 'actor' },
	{ title: 'Jennifer Lawrence', category: 'actor' },
	{ title: 'Scarlett Johansson', category: 'actor' },
	{ title: 'Emma Stone', category: 'actor' },
	{ title: 'Emma Watson', category: 'actor' },
	{ title: 'Anne Hathaway', category: 'actor' },
	{ title: 'Natalie Portman', category: 'actor' },
	{ title: 'Margot Robbie', category: 'actor' },
	{ title: 'Saoirse Ronan', category: 'actor' },
	{ title: 'Zendaya', category: 'actor' },
	{ title: 'Florence Pugh', category: 'actor' },
	{ title: 'Anya Taylor-Joy', category: 'actor' },
	{ title: 'Brie Larson', category: 'actor' },
	{ title: 'Gal Gadot', category: 'actor' },
	{ title: 'Tessa Thompson', category: 'actor' },
	{ title: 'Tilda Swinton', category: 'actor' },
	{ title: 'Frances McDormand', category: 'actor' },
	{ title: 'Helen Mirren', category: 'actor' },
	{ title: 'Judi Dench', category: 'actor' },
	{ title: 'Salma Hayek', category: 'actor' },
	{ title: 'Penélope Cruz', category: 'actor' },
	{ title: 'Marion Cotillard', category: 'actor' },

	// ── Musicians ──────────────────────────────────────────────────────────────
	{ title: 'Beyoncé', category: 'musician' },
	{ title: 'Taylor Swift', category: 'musician' },
	{ title: 'Rihanna', category: 'musician' },
	{ title: 'Adele', category: 'musician' },
	{ title: 'Billie Eilish', category: 'musician' },
	{ title: 'Lady Gaga', category: 'musician' },
	{ title: 'Ariana Grande', category: 'musician' },
	{ title: 'Dua Lipa', category: 'musician' },
	{ title: 'Olivia Rodrigo', category: 'musician' },
	{ title: 'Sabrina Carpenter', category: 'musician' },
	{ title: 'Bruno Mars', category: 'musician' },
	{ title: 'The Weeknd', category: 'musician' },
	{ title: 'Drake (musician)', category: 'musician' },
	{ title: 'Kendrick Lamar', category: 'musician' },
	{ title: 'Travis Scott', category: 'musician' },
	{ title: 'Post Malone', category: 'musician' },
	{ title: 'Ed Sheeran', category: 'musician' },
	{ title: 'Justin Bieber', category: 'musician' },
	{ title: 'Harry Styles', category: 'musician' },
	{ title: 'Bad Bunny', category: 'musician' },
	{ title: 'Shakira', category: 'musician' },
	{ title: 'Jennifer Lopez', category: 'musician' },
	{ title: 'Mariah Carey', category: 'musician' },
	{ title: 'Madonna', category: 'musician' },
	{ title: 'Bono', category: 'musician' },
	{ title: 'Mick Jagger', category: 'musician' },
	{ title: 'Paul McCartney', category: 'musician' },
	{ title: 'Bob Dylan', category: 'musician' },
	{ title: 'Elton John', category: 'musician' },
	{ title: 'Stevie Wonder', category: 'musician' },
	{ title: 'Pharrell Williams', category: 'musician' },
	{ title: 'Snoop Dogg', category: 'musician' },
	{ title: 'Jay-Z', category: 'musician' },
	{ title: 'Eminem', category: 'musician' },
	{ title: 'Kanye West', category: 'musician' },

	// ── Athletes ───────────────────────────────────────────────────────────────
	{ title: 'LeBron James', category: 'athlete' },
	{ title: 'Stephen Curry', category: 'athlete' },
	{ title: 'Kevin Durant', category: 'athlete' },
	{ title: 'Giannis Antetokounmpo', category: 'athlete' },
	{ title: 'Nikola Jokić', category: 'athlete' },
	{ title: 'Luka Dončić', category: 'athlete' },
	{ title: 'Lionel Messi', category: 'athlete' },
	{ title: 'Cristiano Ronaldo', category: 'athlete' },
	{ title: 'Kylian Mbappé', category: 'athlete' },
	{ title: 'Neymar', category: 'athlete' },
	{ title: 'Erling Haaland', category: 'athlete' },
	{ title: 'Mohamed Salah', category: 'athlete' },
	{ title: 'Serena Williams', category: 'athlete' },
	{ title: 'Venus Williams', category: 'athlete' },
	{ title: 'Naomi Osaka', category: 'athlete' },
	{ title: 'Coco Gauff', category: 'athlete' },
	{ title: 'Novak Djokovic', category: 'athlete' },
	{ title: 'Rafael Nadal', category: 'athlete' },
	{ title: 'Roger Federer', category: 'athlete' },
	{ title: 'Tom Brady', category: 'athlete' },
	{ title: 'Patrick Mahomes', category: 'athlete' },
	{ title: 'Aaron Rodgers', category: 'athlete' },
	{ title: 'Megan Rapinoe', category: 'athlete' },
	{ title: 'Simone Biles', category: 'athlete' },
	{ title: 'Usain Bolt', category: 'athlete' },
	{ title: 'Tiger Woods', category: 'athlete' },
	{ title: 'Lewis Hamilton', category: 'athlete' },
	{ title: 'Max Verstappen', category: 'athlete' },
	{ title: 'Conor McGregor', category: 'athlete' },
	{ title: 'Shohei Ohtani', category: 'athlete' },

	// ── Politicians & world figures ────────────────────────────────────────────
	{ title: 'Barack Obama', category: 'politician' },
	{ title: 'Michelle Obama', category: 'politician' },
	{ title: 'Joe Biden', category: 'politician' },
	{ title: 'Kamala Harris', category: 'politician' },
	{ title: 'Donald Trump', category: 'politician' },
	{ title: 'Hillary Clinton', category: 'politician' },
	{ title: 'Bill Clinton', category: 'politician' },
	{ title: 'Alexandria Ocasio-Cortez', category: 'politician' },
	{ title: 'Bernie Sanders', category: 'politician' },
	{ title: 'Justin Trudeau', category: 'politician' },
	{ title: 'Emmanuel Macron', category: 'politician' },
	{ title: 'Angela Merkel', category: 'politician' },
	{ title: 'Olaf Scholz', category: 'politician' },
	{ title: 'Volodymyr Zelenskyy', category: 'politician' },
	{ title: 'Rishi Sunak', category: 'politician' },
	{ title: 'Keir Starmer', category: 'politician' },
	{ title: 'Jacinda Ardern', category: 'politician' },

	// ── Tech / business ────────────────────────────────────────────────────────
	{ title: 'Elon Musk', category: 'business' },
	{ title: 'Jeff Bezos', category: 'business' },
	{ title: 'Bill Gates', category: 'business' },
	{ title: 'Mark Zuckerberg', category: 'business' },
	{ title: 'Sundar Pichai', category: 'business' },
	{ title: 'Satya Nadella', category: 'business' },
	{ title: 'Tim Cook', category: 'business' },
	{ title: 'Sam Altman', category: 'business' },
	{ title: 'Jensen Huang', category: 'business' },
	{ title: 'Sheryl Sandberg', category: 'business' },
	{ title: 'Warren Buffett', category: 'business' },
	{ title: 'Oprah Winfrey', category: 'business' },
	{ title: 'Mark Cuban', category: 'business' },

	// ── TV / talk-show / cultural ──────────────────────────────────────────────
	{ title: 'Ellen DeGeneres', category: 'tv' },
	{ title: 'Jimmy Fallon', category: 'tv' },
	{ title: 'Jimmy Kimmel', category: 'tv' },
	{ title: 'Stephen Colbert', category: 'tv' },
	{ title: 'John Oliver', category: 'tv' },
	{ title: 'Trevor Noah', category: 'tv' },
	{ title: 'Conan O\'Brien', category: 'tv' },
	{ title: 'Jon Stewart', category: 'tv' },
	{ title: 'Anderson Cooper', category: 'tv' },
	{ title: 'Gordon Ramsay', category: 'tv' },
	{ title: 'David Attenborough', category: 'tv' },
	{ title: 'Neil deGrasse Tyson', category: 'tv' },

	// ── Royals & known faces ───────────────────────────────────────────────────
	{ title: 'Prince William, Prince of Wales', category: 'royal' },
	{ title: 'Catherine, Princess of Wales', category: 'royal' },
	{ title: 'Prince Harry, Duke of Sussex', category: 'royal' },
	{ title: 'Meghan, Duchess of Sussex', category: 'royal' },
	{ title: 'King Charles III', category: 'royal' },

	// ── Directors & creators ───────────────────────────────────────────────────
	{ title: 'Steven Spielberg', category: 'director' },
	{ title: 'Christopher Nolan', category: 'director' },
	{ title: 'Quentin Tarantino', category: 'director' },
	{ title: 'Martin Scorsese', category: 'director' },
	{ title: 'Greta Gerwig', category: 'director' },
	{ title: 'Jordan Peele', category: 'director' },
	{ title: 'Bong Joon-ho', category: 'director' },
	{ title: 'Guillermo del Toro', category: 'director' },
	{ title: 'Wes Anderson', category: 'director' },
	{ title: 'Taika Waititi', category: 'director' },

	// ── Writers / thinkers ─────────────────────────────────────────────────────
	{ title: 'Stephen King', category: 'writer' },
	{ title: 'J. K. Rowling', category: 'writer' },
	{ title: 'Margaret Atwood', category: 'writer' },
	{ title: 'Malcolm Gladwell', category: 'writer' },
]
